from datetime import datetime
import re
from pathlib import Path

SRC = Path("src")
DIST = Path("dist")
OUT = DIST / "mission_framework.lua"

FILES = [
    "core.lua",
    "logger.lua",
    "rng.lua",
    "config.lua",
    "generated_version.lua",
    "fog_manager.lua",
    "main.lua",
]

def read_version():
    text = (SRC / "config.lua").read_text(encoding="utf-8")

    match = re.search(r'Version\s*=\s*"([^"]+)"', text)

    if not match:
        return "0.0.0"

    return match.group(1)

def write_generated_version():
    version, build_id = build_version()
    content = f'''-- Auto-generated. Do not edit.
MissionFramework = MissionFramework or {{}}
MissionFramework.Build = {{
    Version = "{version}",
    BaseVersion = "{read_version()}",
    BuildId = "{build_id}"
}}
'''
    (SRC / "generated_version.lua").write_text(content, encoding="utf-8")
    return version

def build_version():
    base = read_version()
    build_id = datetime.now().strftime("%Y%m%d.%H%M")
    return f"{base}+{build_id}", build_id

def build() -> None:
    version = write_generated_version()
    DIST.mkdir(parents=True, exist_ok=True)
    write_kneeboard(version)

    with OUT.open("w", encoding="utf-8") as out:
        out.write(f"-- MissionFramework {version}\n")
        out.write("-- Auto-generated file\n\n")
        out.write("-- Do not edit this file directly.\n\n")

        for filename in FILES:
            path = SRC / filename

            if not path.exists():
                raise FileNotFoundError(f"Missing source file: {path}")

            out.write("\n")
            out.write("-- =========================================================\n")
            out.write(f"-- BEGIN {filename}\n")
            out.write("-- =========================================================\n\n")
            out.write(path.read_text(encoding="utf-8"))
            out.write("\n\n")
            out.write("-- =========================================================\n")
            out.write(f"-- END {filename}\n")
            out.write("-- =========================================================\n\n")
            
   
def write_kneeboard(version):
    path = DIST / "kneeboard_version.txt"
    path.write_text(
        f"MissionFramework\nVersion: {version}\n",
        encoding="utf-8"
    )
   
    print(f"Built {OUT}")

if __name__ == "__main__":
    build()